### PR TITLE
Handle interrupts in the MMU device framework

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
Except shifter and FDC.

### CODE REVIEW

**Comment by stefanberndtsson** [comment]
What is the thought process behind the move of interrupts to MMU? In reality this is handled by GLUE. MMU does not interrupt the CPU at all (even Bus Error is triggered by GLUE).

Why the exception of the shifter and FDC? FDC isn't connected via the MMU, but the shifter is. FDC does its interrupts via MFP (not GLUE directly), and shifter doesn't actually do interrupts at all. GLUE handles all the video interrupts by itself.

**Comment by larsbrinkhoff** [comment]
The primary motivation was to include interrupts in the "device model".

I moved this to the MMU, because there is a big overlap between `struct mmu` and those devices that generate interrupts.  Also, `mmu.c` has `mmu_do_interrupts`, making it the current hub of interrupt activity.  In my opinition, there might be a new `struct device` to model all hardware devices, and if so interrupts would be part of that.

Currently, there is no GLUE in the code, otherwise I might have made some changes there.

The shifter was excepted because it doesn't do interrupts the way all other devices do, i.e. in `mmu_do_interrupts`.  It's true that the hardware shifter doesn't do interrupts, but `shifter.c` does have `shifter_do_interrupts`.  Not my fault! :-)

The FDC was excepted, because it doesn't have a `struct mmu`.

**Comment by stefanberndtsson** [comment]
I'm not blaming you. :)

I think I'm leaning towards implementing a GLUE, and thereby making the shifter simpler too. All the ```shifter_on_display``` or whatever the name was would be handled in the GLUE instead.

But that will take a bit of time, so maybe this is a reasonable thing until then.

**Comment by larsbrinkhoff** [comment]
That sounds nice.

This pull request isn't perfect, but I think it takes a small step in the right direction.

**Pull request merged**
